name: Release bookget

on:
  push:
    tags: [ "v*" ]
jobs:
  build:
    strategy:
      matrix:
        platform:
          - linux-amd64
          - linux-arm64
          - darwin-amd64
          - darwin-arm64
          - windows-amd64
    runs-on: ${{
      contains(matrix.platform, 'linux') && 'ubuntu-latest' ||
      contains(matrix.platform, 'darwin') && 'macos-latest' ||
      'windows-latest'}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Make (Windows)
        if: runner.os == 'Windows'
        run: choco install make -y

      - name: Build
        run: |
          make ${{ matrix.platform }}

      - name: Verify artifacts
        run: ls -R dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bookget-${{ matrix.platform }}
          path: dist/${{ matrix.platform }}/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # å¿…é¡»æ·»åŠ è¿™ä¸ªæƒé™
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: List files for debugging
        run: find dist/ -type f

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}  # æ›¿æ¢é»˜è®¤çš„GITHUB_TOKEN
          tag_name: ${{ github.ref_name }}
          name: "bookget ${{ github.ref_name }}"
          body: "|
ğŸš€ Automated release by **github-actions[bot]**  
      
**Assets:**
- Linux: `bookget-linux` / `bookget-linux-arm64`
- Windows: `bookget.exe`
- MacOS: `bookget-macos` / `bookget-macos-arm64`
      "
          files: |
            dist/**/bookget*
